### ISSUE TITLE
PMD not removing warnings after filter

### ISSUE THREAD

**Issue by pkrall520** [pmd/pmd-eclipse-plugin#102]
Hello,
Our application recently upgraded to the latest PMD plugin and we are noticing a bunch of PMD markers showing in the eclipse problems tab. ( We LOVE them ). For some of our projects we only want to be PMD level 1 or 2 compliant. When we filter the problems tab as shown below, the PMD markers still show all the warnings not just the ones we care about. Is there a fix for this? We had this before with the old markers.

![image](https://user-images.githubusercontent.com/8525633/58601225-e954f180-8255-11e9-997e-36f1437ba343.png)

![image](https://user-images.githubusercontent.com/8525633/58601240-fffb4880-8255-11e9-9c48-0953e0043163.png)

**Comment by adangel** [comment]
I also first ran into this problem, but it's actually eclipse, that is a bit unintuitive here: If you keep the checkbox "Show all item" selected, then anything you configure here has no effect...

I'd recommend to create a new configuration with the button "New", rename it to "Only PMD Prio 1+2", then select it on the left and then change the markers on the right (deselect all and only select the two PMD prios):

![grafik](https://user-images.githubusercontent.com/1573684/58620655-e98dd500-82c7-11e9-83dc-5cf266cf73f8.png)
