### ISSUE TITLE
Duplicate entries in reports

### ISSUE THREAD

**Issue by fakiliarda** [pmd/pmd-eclipse-plugin#109]
Hi!,

I am new at PMD, and I'm trying to generate a report in summaryhtml format. But when i generate it, it gives a report that all problems are duplicated. Am i do anything wrong or is it a bug?

I tried to generate another formats and I got the same result.

![prb](https://user-images.githubusercontent.com/42325658/61128860-ba1fda00-a4bb-11e9-8b07-c8d1a410001c.PNG)

**Comment by nagadheerajb** [comment]
Hello fakiliarda

I am facing the same issue. Did the issue got resolved to you?

Regards
Naga

**Comment by fakiliarda** [comment]
Hello Naga,I really don't remember, it was a long time ago. Sorry.
-------- Orijinal mesaj --------Kimden: nagadheerajb ***@***.***> Tarih: 15.11.2022  08:00  (GMT+03:00) Alıcı: pmd/pmd-eclipse-plugin ***@***.***> Cc: Arda Fakılı ***@***.***>, Author ***@***.***> Konu: Re: [pmd/pmd-eclipse-plugin] Duplicate report entries summaryreport.html (#109) 
Hello fakiliarda
I am facing the same issue. Did the issue got resolved to you?
Regards
Naga
