### ISSUE TITLE
PMD does not automatically check in Eclipse when java file is saved

### ISSUE THREAD

**Issue by krallus** [pmd/pmd-eclipse-plugin#121]
I only recently started noticing this issue but, admittedly, I've also only started using Eclipse in Windows (Linux is my norm).

## Environment
Windows 10
Eclipse IDE for Enterprise Java Developers 2020-03 (4.15.0)
PMD Plug-in 4.12.0.v20200424-1006

## Recreate
One simple way to recreate the problem (though the problem is a general one):
Save a .java file containing a method with a parameter that is not "final".
**Expected behaviour**: the line should be marked by PMD with "MethodArgumentCouldBeFinal".
**Actual behaviou**r: the line is not marked by PMD

## Workarounds
PMD will still do the checking and marking with either of these actions:

- Right click on project=>PMD=>Check Code
- Project=>Clean (when "build automatically" is enabled)

Note that I did check the Project Natures and "PMD Nature" is present.  Also PMD's "Full build enabled" is checked in the project.

**Comment by krallus** [comment]
Gah! I'd delete this if I could! I didn't have "check code after saving" enabled.

**Comment by adangel** [comment]
Just for completeness:
* Window->Preferences->PMD->Check Code After Saving:
  * if yes: Run PMD, when you save a file **unless** Project->Build Automatically is active - then PMD is run via the PMD project builder
  * if no: Then PMD is never run, neither via the save hook nor via the project builder.
* Project->Build Automatically
  * if yes: this will call the project builders for every changed file (incremental build)
  * if no: no project builders are executed. But resource change handlers are (and PMD as a listener attached)
* Project->Clean... does a full rebuild of the project. In that case, also the project builders are called (independent of the Project->Build Automatically setting).
