### ISSUE TITLE
Updates with outdated certificates from orbit

### ISSUE THREAD

**Issue by 2019-05-10** [pmd/pmd-eclipse-plugin#133]
tried to install from the given update site url
https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/
got a warning about unsigned files and next the question whether to trust a certificate

the tree of certificates has expiration dates all over the place:
2012, 2026, 2015, 2018, 2016

I am not sure what to make of that.

![image](https://user-images.githubusercontent.com/50481865/95728302-a5f8f880-0c7b-11eb-9be4-d2c536d4c27c.png)

**Comment by adangel** [comment]
With the fix for #134 we don't need the orbit repository at all anymore. So I'll just remove it.
