### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by alikunda** [pmd/pmd-eclipse-plugin#160]
Hi, I need help with running this project, I have installed it as maven project but I not very familiar with plugins and how it works, I am trying to run it but there is not selection as an error, can provide me the steps after importing how can I run the project locally to check instead of downloading it from marketplace

**Comment by adangel** [comment]
Thanks for your question. Could you please clarify, what you mean by "running this project"?

Do you want to use PMD as a user to find potential programming mistakes? Then download the update site from https://github.com/pmd/pmd-eclipse-plugin/releases/latest and install it via "Help", "Install new Software...".

Do you want to develop PMD Eclipse Plugin (e.g. fix issues, improve UI, dialogs, etc.)? Then you please read https://github.com/pmd/pmd-eclipse-plugin#short-developers-guide

**Comment by alikunda** [comment]
@adangel  I want to develop the plugin, but after making changes how can I use or install my updated code for the plugin to test or for use?

Thank you.

**Comment by adangel** [comment]
> Simply run `./mvn clean verify`. The plugin's update site will be generated in `net.sourceforge.pmd.eclipse.p2updatesite/target/repository`. You can use this directory as an update site to install the new plugin version directly into your Eclipse.

That's the easiest way. There are also ways, to run a new eclipse with the current plugin under development - but that's described at https://help.eclipse.org/latest/topic/org.eclipse.pde.doc.user/guide/tools/launchers/eclipse_application_launcher.htm?cp=4_3_3_0

> A quick way to test a plug-in is by launching a separate application via Eclipse Application launch shortcuts that are available as:
>
> *    hot links in the Testing section of the plug-in manifest editor's Overview page
> *    actions in the Run As > and Debug As > context menus of plug-in projects

Hope that helps.

**Comment by alikunda** [comment]
Thanks @adangel That helps me understanding how to run it, But for the first option './mvn clean verify', where do I have to execute this command in CMD? or in eclipse for 'net.sourceforge.pmd.eclipse.plugin'?, I also have tried to Run As 'Maven clean Build' in the options, but that didn't work as I cannot see the updated site  'net.sourceforge.pmd.eclipse.p2updatesite/target/repository'.

**Comment by adangel** [comment]
You need to run it in a terminal. Full sequence:

```
git clone https://github.com/pmd/pmd-eclipse-plugin
cd pmd-eclipse-plugin
./mvnw clean verify
```

If you are working under Windows, you should use [git-bash](https://gitforwindows.org/), then the commands are exactly the same. 

You can also run as maven build from within eclipse ("run as maven ..."). You'll need to run this on the parent project "net.sourceforge.pmd.eclipse.parent".
