### ISSUE TITLE
Missing constraints in runtime Eclipse workspace (e.g., in Eclipse Modeling Tool since 2022-12 R)

### ISSUE THREAD

**Issue by maxkratz** [pmd/pmd-eclipse-plugin#168]
### Issue
Currently, the PMD Eclipse plugin creates an error message when starting a runtime workspace from, e.g., **Eclipse Modeling Tools** since 2022-12 R (https://www.eclipse.org/downloads/packages/release/2022-12/r/eclipse-modeling-tools). This was not the case for the releases 2022-09 and 2022-06. I will append the error message as a screenshot.

### Reproduction
To reproduce the error, follow these steps:
- Download Eclipse Modeling Tools 2022-12 R (e.g., from the link above).
- Start it and create an empty workspace.
- Within the workspace, click on `Run Configurations...`.
- Double-click on the entry `Eclipse Application` in the left menu.
- You can leave all default settings and click the button `Run`.
- See the error window (should be the same as in the screenshot).

Is there any way for me to resolve this issue or is this a bug/missing dependency within the PMD Eclipse plugin?

Thank you for your help.

---
Screenshot showing the error message:
![pmd-apache-validator-error](https://user-images.githubusercontent.com/20956405/207264710-88e43f5a-d324-4bfd-9234-592631506b90.png)

**Comment by adangel** [comment]
Thanks for the report.

In your reproduction steps, I don't see, when the PMD plugin comes into the play... or is it included in the Eclipse Modeling Tools distribution by default?

Hm... okay, I can reproduce the case, when install the PMD plugin.

The screenshot shows, that the bundle "org.apache.xml.resolver" requires the package "javax.xml.parsers". When creating a run configuration for an Eclipse Application, eclipse will use whatever target platform is configured, to resolve any dependency. If no specific target platform is configured, I think, eclipse defaults to the "running eclipse" itself.

The missing packages are "standard" java packages like java.xml.parsers. These are provided usually by the execution environment. If the running eclipse is used as the target platform, then it defaults to whatever Java version is shipped with eclipse.

For Java 17, the packages are in the module "java.xml": https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/module-summary.html#packages-summary

As I see, the default execution environment is Java 17 and eclipse uses a standard openjdk hotspot jre. I see no reason, why xml wouldn't be available here.

Regarding the dependencies, it seems to be that way:
* net.sourceforge.pmd.eclipse.plugin needs org.eclipse.wst.xml.core
* org.eclipse.wst.xml.core needs org.apache.xerces
* org.apache.xerces needs packages org.apache.xml.resolver and org.apache.xml.resolver.readers
* org.apache.xml.resolver provides these packages and needs javax.xml.parsers etc.

We could try to replace the dependency to org.eclipse.wst.xml.core in the PMD plugin to package import "javax.xml", maybe that helps. And I don't know, why we would need org.eclipse.wst...

But I still don't understand, why javax.xml wouldn't be available. This sounds more like a eclipse PDE issue...

**Comment by maxkratz** [comment]
> In your reproduction steps, I don't see, when the PMD plugin comes into the play... or is it included in the Eclipse Modeling Tools distribution by default?
> 
> Hm... okay, I can reproduce the case, when install the PMD plugin.

Okay, I missed mentioning that: I installed the PMD plugin from its update site manually. It is not included in Eclipse Modeling Tools. You are right.

> The screenshot shows, that the bundle "org.apache.xml.resolver" requires the package "javax.xml.parsers". When creating a run configuration for an Eclipse Application, eclipse will use whatever target platform is configured, to resolve any dependency. If no specific target platform is configured, I think, eclipse defaults to the "running eclipse" itself.
> 
> The missing packages are "standard" java packages like java.xml.parsers. These are provided usually by the execution environment. If the running eclipse is used as the target platform, then it defaults to whatever Java version is shipped with eclipse.
> 
> For Java 17, the packages are in the module "java.xml": https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/module-summary.html#packages-summary
> 
> As I see, the default execution environment is Java 17 and eclipse uses a standard openjdk hotspot jre. I see no reason, why xml wouldn't be available here.

Yes, I'm also confused why XML would not be available at runtime.

> Regarding the dependencies, it seems to be that way:
> 
> * net.sourceforge.pmd.eclipse.plugin needs org.eclipse.wst.xml.core
> * org.eclipse.wst.xml.core needs org.apache.xerces
> * org.apache.xerces needs packages org.apache.xml.resolver and org.apache.xml.resolver.readers
> * org.apache.xml.resolver provides these packages and needs javax.xml.parsers etc.
> 
> We could try to replace the dependency to org.eclipse.wst.xml.core in the PMD plugin to package import "javax.xml", maybe that helps. And I don't know, why we would need org.eclipse.wst...

If you want to, I can test it if you can provide me, e.g., a ZIP file with a test update site.

> But I still don't understand, why javax.xml wouldn't be available. This sounds more like a eclipse PDE issue...

- Are there some steps for me to test the availability of javax.xml with another plugin or ... ?
- Should I open an issue at Eclipse PDE?

Thank you for your time!

**Comment by adangel** [comment]
I've experimented a bit now, but don't fully understand the problem. When I install the feature "XML, DTD and XML Schema Editors, wizards, validators, and XML Catalog support" (org.eclipse.wst.xml_ui.feature), which includes "org.eclipse.wst.xml.core", before I install PMD plugin, then the problem doesn't appear. Then an additional plugin is installed, it's "JAXP XML" (bundle id: javax.xml) from [Eclipse Orbit](https://download.eclipse.org/tools/orbit/downloads/drops/R20201130205003/). That's an old implementation of the javax.xml.* namespace. It's installed, but apparently not used by any other plugin - not even by "org.apache.xml.resolver", which imports javax.xml.parsers from the platform system bundle (org.eclipse.osgi). Like all other plugins do - since javax.xml is provided by the system bundle.

I found the following bugs on eclipse side, which sound similar: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512599 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=512424
Apparently, the check for the run configuration ("Validate Plug-ins") might not use the correct execution environment. In Java versions before 1.4, there was no JAXP bundled (https://en.wikipedia.org/wiki/Java_API_for_XML_Processing), so this Orbit bundle "JAXP XML/javax.xml" was indeed needed back then. And somehow PDE still thinks, it's needed...

Anyway, I'm going to remove the dependency from PMD plugin to "org.eclipse.wst.xml.core" entirely, as it is not needed. This should solve the issue.

**Comment by adangel** [comment]
@maxkratz I think, this is fixed now. Can you try with the snapshot from here? https://pmd.github.io/pmd-eclipse-plugin-p2-site/snapshot/

The fix will be included in the next release.

**Comment by maxkratz** [comment]
> @maxkratz I think, this is fixed now. Can you try with the snapshot from here? https://pmd.github.io/pmd-eclipse-plugin-p2-site/snapshot/
> 
> The fix will be included in the next release.

I've checked it on my machine and the dependency error/window is gone. Thank you for the fast fix!

Do you know approx. when the next release will be ready?

**Comment by adangel** [comment]
Thanks for testing!

I plan to release the next version end of this year.

**Comment by maxkratz** [comment]
Looking forward to it!
