### ISSUE TITLE
Unable to install PMD Eclipse Plugin from update site

### ISSUE THREAD

**Issue by MarcoLasticot** [pmd/pmd-eclipse-plugin#19]
### https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/

----

I'm unable to install PMD Eclipse Plugin from update site on Eclipse NEON 2

Tried:

- https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/

- https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/

- http://netassist.dl.sourceforge.net/project/pmd/pmd-eclipse/update-site-latest/

Still the same error:
Unable to read repository at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/content.xml.
Unable to read repository at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/content.xml.
Received fatal alert: handshake_failure

**Comment by adangel** [comment]
This handshake_failure might be a certificate problem. Make sure, you use jdk 8 update 111 or later, otherwise java doesn't accept Let's Encrypt certificates.

Sourceforge Mirrors behave very undeterministic (e.g. files might exist or might not...). The easiest workaround is, to download the update site as a zip archive from https://github.com/pmd/pmd-eclipse-plugin/releases , unpack it locally and use this folder as an update site.


See also https://github.com/pmd/pmd/issues/187

**Comment by adangel** [comment]
> @adangel maybe we should consider publishing the update site to http://pmd.github.io/ ?

**Comment by dolhim** [comment]
This link is working on my neon2
- http://netassist.dl.sourceforge.net/project/pmd/pmd-eclipse/update-site-latest/

Thank you.

ps. 
but, those not working for me neither :
- https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/
- https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/

same error with marco

**Comment by winters1224** [comment]
This link is unavailable on my neon2:

http://netassist.dl.sourceforge.net/project/pmd/pmd-eclipse/update-site-latest/

and my Eclipse is:
Version: Neon.2 (4.6.2)
Build id: M20161124-1400


I download a zip archive from https://github.com/pmd/pmd-eclipse-plugin/releases and it works.

thanks all

**Comment by egry35** [comment]
hello,

like dolhim, this link is ok for me on my neon2 :
http://netassist.dl.sourceforge.net/project/pmd/pmd-eclipse/update-site-latest/

and my Eclipse is:
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600


But I think you should update "Eclipse marketplace" to allow developers to install "pmd-eclipse-plugin" with Eclipse MarketPlace (my first attempt was to use eclipse marketplace and i saw that this plugin wasn't migrated for Neon)

**Comment by Niceplace** [comment]
I am also getting the SSL certificates error 

```
!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2017-03-09 13:24:23.896
!MESSAGE Unable to read repository at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/content.xml.
!STACK 0
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:435)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:216)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.layerProtocol(ManagedClientConnectionImpl.java:394)
	at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:814)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:615)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

java version "1.8.0_121"

Trying to install with eclipse neon 2

**Comment by adangel** [comment]
Crossposting the solution from http://stackoverflow.com/questions/42128981/eclipse-pmd-plug-in-handshake-failure 

> It's probably one of the following two cases:
>
>    Either the cipher is not supported by your JRE - see answer http://stackoverflow.com/a/42129608/1169968 to install the JCE security patch to allow unlimited security (local_policy.jar and US_export_policy.jar)
>
>    The JRE version, you are using, doesn't trust Let's Encrypt certificates, that are used by some of the sourceforge mirrors. You need at least Java 7 Update 111 or Java 8 Update 101. See https://letsencrypt.org/docs/certificate-compatibility/

Can you try to install the JCE patch? -> http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by Niceplace** [comment]
Thank you for your solution @adangel ! I was able to implement a specific one for Ubuntu 16.04
However, I have to note that the installation time is astronomically high, I don't understand why ...

I use the webupd8 repository for java and this package is available for installation via apt

Steps to completely install java8
(I recommend nuking java 7 if it is installed by default on the system)

Add webupd8 repo

```
su -
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
```

Install java 8 and jce-policy

```
sudo apt-get install oracle-java8-installer
sudo apt-get install ca-certificates
sudo apt-get install oracle-java8-set-default
sudo apt-get install oracle-java8-unlimited-jce-policy
```

**Comment by creckord** [comment]
Note that despite Let's Encrypt's claim,  Java 8 Update 101 does not seem to contain the proper root certificates. Java 8 Update 121 worked for me, earlier ones might as well. Some mirrors also seem to require the JCE unlimited strength policy due to updated ciphers, others apparently don't.

If you can't update your Java, you can import the root certs either into your global trust store or create a custom trust store for your Eclipse. See https://t.co/wnMXTRRjSs for a step-by-step.

In general, I would agree though that moving away from SF as host for the update site might be a good idea.

**Comment by adangel** [comment]
I've configured a new update site at bintray. Please use from now on https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/

Requests, that come through to sourceforge, will be redirected to the new site.

Please comment/reopen the issue, if you still experience problems. Thanks!

**Comment by rallengrc** [comment]
Just had this problem in 2021 with openjdk 1.8.0_282 on mac osx 10.15.7 with SpringToolSuite 4.11.1 and I had to install the JCE patch? -> http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by adangel** [comment]
Please note, that the update site moved to github since April 2021 - please use https://pmd.github.io/pmd-eclipse-plugin-p2-site/

All the updates site you mentioned don't work because they don't exist anymore.

The current update site urls are:
PMD: https://pmd.github.io/pmd-eclipse-plugin-p2-site/
Checkstyle: https://checkstyle.org/eclipse-cs-update-site

**Comment by aos0020** [comment]
gracias @adangel you solved for me.
