### ISSUE TITLE
Not getting Complete PMD options with the plugin in ADT

### ISSUE THREAD

**Issue by srib4ufrnd** [pmd/pmd-eclipse-plugin#2]
HI,

I started using PMD recently for code style checking.

I got the eclipse plug in link and added the plug in site succesfully.

PMD is succesfully installed.

But the issue is below.

When i right click -> select src folder in project explorer -> PMD

I am getting only 3 options.

I am not getting complete PMD options.

I am ctually looking for "Generate reports" option so that i can generate PMD reports from eclipse.

This is not listing for me.

I am using the below machine deatils

Winidows - 7 SP1
i7
8gb
64 bit OS

I am using ADT - android developer tool - which intern using eclipse Juno.

Eclipse platform is: 
Version: 4.2.1.v20130118-173121-9MF7GHYdG0B5kx4E_SkfZV-1mNjVATf67ZAb7
Build id: M20130204-1200

Please see the bug image below.

Is this happenning because of any eclipse platfrom dependancy. Could some one please resolve this issue.

Please provide any solution is any one knows. I could not find any documentation for enabling extra options.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/686563/4369898/4b357bba-4302-11e4-956e-f68015ee4625.png)

**Comment by kumarP1980** [comment]
I have installed PMD plugin 4.24.0 and still having the same issue as described above.
![image](https://user-images.githubusercontent.com/58350714/123152421-9220ab80-d432-11eb-8925-31d1fd727bdf.png)
I don't see Generate Report option for the individual file.
![image](https://user-images.githubusercontent.com/58350714/123152706-d9a73780-d432-11eb-84a4-ec642302a692.png)

**Comment by adangel** [comment]
As mentioned in the last comment, this is simply not implemented - hence I consider this a feature request.
Please open a new issue and describe the feature you want (e.g. "I want to create a PMD report for a single file. Currently the context menu item "Generate Reports" only appears for whole projects").
Thanks!
