### ISSUE TITLE
Global Rule Configuration not rendering properly on Neon 

### ISSUE THREAD

**Issue by grandinj** [pmd/pmd-eclipse-plugin#27]
Version Info:
  Eclipse: Neon.3 Release (4.6.3) 
  OS: Windows 10 64-bit
  Java: 1.8.0_45-b15

![image](https://user-images.githubusercontent.com/796121/29208143-20fe1008-7e89-11e7-8d25-dfeaf8b8dec8.png)

**Comment by grandinj** [comment]
The checkboxes are invisible, and I suspect the row heights are wrong

**Comment by adangel** [comment]
@grandinj Thanks for the report. Can you try how it looks, if you enable the checkbox at the top "Use global rule management"? If the global rule management is not enabled, then the lower part of the dialog is disabled as well - so the weird appearance might be cause by the disabled states of the controls.

**Comment by grandinj** [comment]
I just re-installed PMD (1.10.0) and now the only PMD page I have available is the one in Project Properties. 

Can't find the Global Rule Configuration page anymore. 

Can't find find any rule sets either.

No errors in the Eclipse error log.

**Comment by adangel** [comment]
There are two PMD plugins available: This one here called "pmd-eclipse" and the alternative [eclipse-pmd](https://acanda.github.io/eclipse-pmd/). You've installed now the alternative - hence the UI to completely different ;-)

**Comment by grandinj** [comment]
Doh! I'm an idiot. Thanks for that.

OK, installed the right thing, If I enable "Global rule management", I can activate and de-activate rules by clicking on where the checkboxes should be ( I can tell because the active rule count changes ), but the checkboxes remain invisible.

**Comment by adangel** [comment]
Neon won't be supported anymore. Since 7.0.0-rc1, only the last 4 eclipse versions will be supported.
See https://github.com/pmd/pmd-eclipse-plugin/releases/tag/7.0.0.v20230410-1321-rc1
