### ISSUE TITLE
pmd plugin greatly slows down project import 

### ISSUE THREAD

**Issue by farnetto** [pmd/pmd-eclipse-plugin#31]
The pmd-eclipse-plugin slows down the project import greatly, apparently because it is invoked many times and/or runs in parallel. This problem seems to have gotten worse and become severe with Eclipse Oxygen, so much so that this Eclipse release is unusable for us.
Attached is a logfile showing the problem. This shows the process when importing only one small (maven) project with only 87 files.
[pmd-eclipse.log](https://github.com/pmd/pmd-eclipse-plugin/files/1589037/pmd-eclipse.log)

**Comment by farnetto** [comment]
m2e generated .project file attached
[.project.txt](https://github.com/pmd/pmd-eclipse-plugin/files/1591173/default.project.txt)

**Comment by farnetto** [comment]
This doesn't seem to be a specific problem with the PMD plugin. The project import starts *many* full builds at once - eight in the screenshot attached - which lead to just as many full executions of checkstyle, PMD etc. Is this problem with m2e or with oxygen in general? Are there other open issues in those projects dealing with it? Any tips much appreciated.
![grafik](https://user-images.githubusercontent.com/24813634/34435522-93b4095e-ec8e-11e7-99d5-4792e2f750ae.png)

**Comment by farnetto** [comment]
Upgrade to 4.0.16 doesn't solve the problem.

**Comment by adangel** [comment]
@farnetto The memory problem should be fixed with 4.0.17 via #52 . Can you update the plugin and try again? If you still see the problem, please reopen this issue. Thanks!
