### ISSUE TITLE
An internal error occurred during: "ReviewCode".

### ISSUE THREAD

**Issue by ahanekom** [pmd/pmd-eclipse-plugin#34]
When executing the "check code" function on a Java Project I received the following error:

An internal error occurred during: "ReviewCode".

java.lang.NoClassDefFoundError: com/excel4apps/servlet/wand/framework/exceptions/CookieNotFoundException
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.getFieldType(ClassTypeResolver.java:346)
(Full Eclipse Error Log attached)

The issue seems to be related to java projects referencing other java projects in the build path, when the PMD eclipse plugin makes a call to get field types, a java.lang.NoClassDefFoundError is raised. The class reported as not being found, CookieNotFoundException, is not located in the source folder of the Java project being checked, it is part of the project, referenced in the build path.

PMD Plug-in	4.0.15.v20170624-2134	net.sourceforge.pmd.eclipse.feature.group	PMD Project

[ReviewCode Error.log](https://github.com/pmd/pmd-eclipse-plugin/files/1696912/ReviewCode.Error.log)

**Comment by ahanekom** [comment]
Update: When additionally adding the project class folder, Java Build Path -> Libraries Tab: Add Class Folder..., of the project which is already linked via the Projects tab in the Java Build Path dialog, the error is not raised during the Check Code call.

**Comment by ahanekom** [comment]
When disabling the workspace level PMD option "Enable using Java Projects Build Path..." the check code completes successfully without adding the project class folder as commented above. Issue resolved.

**Comment by Androbin** [comment]
Good to know that this "fixes" the issue. But it's a nasty bug nonetheless.
We should use the classpath that Eclipse uses internally to be consistent.
Or at least catch the error and display a human readable error message.

**Comment by adangel** [comment]
Agreed - the way how the eclipse plugin determines the classpath to be used when executing PMD is probably worth more than one look...

**Comment by Androbin** [comment]
Seems the PMD `JavaTypeDefinition` is now swallowing this completely:
https://github.com/pmd/pmd/commit/30afff46c65d17dd4974f4831b1ea0f0232bdf75#diff-01d012be81d194e955a628c70a37287bR69

**Comment by adangel** [comment]
I think, this has been fixed with #96 . Please re-open the issue, if the problem still exists.
