### ISSUE TITLE
https://pmd.github.io/pmd-5.8.0 (404 - Not Found)

### ISSUE THREAD

**Issue by ahanekom** [pmd/pmd-eclipse-plugin#35]
Selecting the "Open in Browser" button on the Show Details Dialog launches against the https://pmd.github.io/pmd-5.8.0 URL, looks like it's been replaced by https://pmd.github.io/pmd-5.8.1

PMD Plug-in	4.0.15.v20170624-2134	net.sourceforge.pmd.eclipse.feature.group	PMD Project

**Comment by adangel** [comment]
See also https://github.com/pmd/pmd/issues/1015 for the explanation.

To save webspace, we only keep the latest bugfixed version online around. Unfortunately the eclipse plugin uses an older version of PMD.

I see the following options:
1. provide an archive of the documentation online at http://pmd.sourceforge.net
2. Make sure to keep the PMD version, that the eclipse plugin uses, updated
3. Provide a redirect after we have removed a specific version from the documentation. This might not be so easy for the github pages.
4. Bundle the documentation in the eclipse plugin itself. Technically, the plugin should already have all the information. The online version is just a different formatting/presentation of the same information.

**Comment by adangel** [comment]
I've now done 1 and 3: the 404 page on pmd.github.io will now redirect to pmd.sourceforge.net, where the old documentation is available. The redirection only works, if javascript is enabled...

Archive Url: http://pmd.sourceforge.net/archive.html

So, 5.8.0 is available at: http://pmd.sourceforge.net/pmd-5.8.0/
