### ISSUE TITLE
"violationsAsErrors" is completely ineffective

### ISSUE THREAD

**Issue by fflatorre** [pmd/pmd-eclipse-plugin#54]
Even instructing the plugin to highlight the violations as errors : 

`<violationsAsErrors>true</violationsAsErrors>`

Violation are still segregated in the PMD view and there is no mention of them in the "Problem" panel.

Not sure if [this](https://github.com/pmd/pmd-eclipse-plugin/blob/13f8ba4709eb13385240d8434e60d186cbc883fc/net.sourceforge.pmd.eclipse.plugin/src/main/java/net/sourceforge/pmd/eclipse/runtime/cmd/BaseVisitor.java#L638) is the incriminated line.

**Comment by adangel** [comment]
The line is correct - it increases the severity to error instead of warning.
But all markers are currently only textmarkers (`org.eclipse.core.resources.textmarker`), which means - they won't show up in the "Problems View"...

**Comment by adangel** [comment]
See also https://sourceforge.net/p/pmd/bugs/1212/ and https://sourceforge.net/p/pmd/bugs/1151/

**Comment by adangel** [comment]
Also relevant here:  https://sourceforge.net/p/pmd/bugs/1359/ -> we'll need a org.eclipse.ui.editors.markerAnnotationSpecification
