### ISSUE TITLE
PMD not filtering

### ISSUE THREAD

**Issue by pkrall520** [pmd/pmd-eclipse-plugin#56]
When I run a check code on a project and I filter out a priority, then I no longer see that filtered priority in my markers which is great. After some time, those filtered markers seem to return and start showing again. 

I have not found a pattern, but it seems more frequent when I branch/ merge code together. Some times it happens when I restart eclipse.

Do we cache those markers in the properties?

**Comment by pkrall520** [comment]
Hi there, 
Sorry for the late reply. 
I would be using the violation overview to filter the markers and I would most likely have build automatically on. 

When we do a new build, do we remove all the markers and then readd the new ones or do we just try to clean up the correct ones?

I have this issue when I branch or merge different versions of the same file. So I am thinking that maybe PMD is seeing an old AST and not the new one? 

Maybe something like the following is happening:
Eclipse starts -> eclipse builds -> PMD runs _>  check out branch -> PMD runs -> eclipse builds..

These are just guesses.. I haven't had free time to look into it.

**Comment by adangel** [comment]
I've had now a look. Here are my findings:

* We save the selected priorities, when the violation overview / violation outline views are closed, e.g. https://github.com/pmd/pmd-eclipse-plugin/blob/f0ddade617634730583afe1779568c95cec50c34/net.sourceforge.pmd.eclipse.plugin/src/main/java/net/sourceforge/pmd/eclipse/ui/views/ViolationOverview.java#L153
* We use different instances of `PriorityFilter` in those two views. So changing the filter on one view doesn't affect the filter on the other view.
* However, changing the filter in violation overview causes PMD to be rerun, using priority filter from violation overview (via `PriorityUtil.isPriorityActive()`)
* Changing the priorities in violations outline changes the priority filter there and the PMD is rerun, but the filter settings from violation overview are used. This means, that the priority filter in violations outline works differently: the violation marker is not removed, but only removed in the violations outline. *I think this is actually the correct behavior*.
