### ISSUE TITLE
Does the plugin work on Eclipse Photon + Java 10.0.2?

### ISSUE THREAD

**Issue by mefoster** [pmd/pmd-eclipse-plugin#59]
Hello all,

I'm trying to install and use the pmd-eclipse-plugin on Eclipse Phonon and Java 10.0.2. However, I am getting a variety of errors and weird behaviours. Before I investigate further: is the plugin expected to work in this configuration at all? Or should I downgrade my Eclipse/Java configuration and wait for a plugin update.

**Comment by adangel** [comment]
Java 10 support in terms of parsing/analyzing code is not yet supported with the PMD version, that is included in the current pmd-eclipse-plugin.
Java 10 support is available with PMD 6.4.0, but the eclipse plugin uses PMD 6.2.0.

However, running eclipse with the plugin under a java10 runtime should not be a problem...

**Comment by mefoster** [comment]
Aha, that explains what I've been seeing -- the plugin installs but doesn't seem to do anything when run. Any idea of an ETA for the updated version? I'd like to use PMD in an educational context in the autumn and must use Java 10 because of the JShell REPL.

_[ Sorry if this comment is duplicated, I thought I had already posted a reply but I don't see it on github ... ]_

**Comment by adangel** [comment]
You can use the snapshot version 4.0.18 from here: https://dl.bintray.com/pmd/pmd-eclipse-plugin/snapshots/updates/
It contains PMD 6.6.0 (see https://github.com/pmd/pmd-eclipse-plugin/blob/master/ReleaseNotes.md#pmd-for-eclipse---release-notes)

**Comment by jftsunami** [comment]
Snapshot 4.0.18 does not appear to work on the release version of 2018-09 / Photon due to a configuration  or dependency issue with log4j

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=10.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/C:/devenv/workspace/ -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
```

```
org.osgi.framework.BundleException: Could not resolve module: net.sourceforge.pmd.eclipse.plugin [1018]
  Bundle was not resolved because of a uses constraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource net.sourceforge.pmd.eclipse.plugin [osgi.identity; osgi.identity="net.sourceforge.pmd.eclipse.plugin"; type="osgi.bundle"; version:Version="4.0.18.v20180919-1800"; singleton:="true"] because it exports package 'org.apache.log4j' and is also exposed to it from resource org.apache.log4j [osgi.identity; type="osgi.bundle"; version:Version="1.2.15.v201012070815"; osgi.identity="org.apache.log4j"] via the following dependency chain:

  net.sourceforge.pmd.eclipse.plugin [osgi.identity; osgi.identity="net.sourceforge.pmd.eclipse.plugin"; type="osgi.bundle"; version:Version="4.0.18.v20180919-1800"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.commons.logging)(bundle-version>=1.0.4))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="1.2.0.v20180409-1502"; osgi.wiring.bundle="org.apache.commons.logging"
  org.apache.commons.logging [osgi.identity; type="osgi.bundle"; version:Version="1.2.0.v20180409-1502"; osgi.identity="org.apache.commons.logging"]
    import: (osgi.wiring.package=org.apache.log4j)
     |
    export: osgi.wiring.package: org.apache.log4j
  org.apache.log4j [osgi.identity; type="osgi.bundle"; version:Version="1.2.15.v201012070815"; osgi.identity="org.apache.log4j"]
	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
```

**Comment by jftsunami** [comment]
Pull request for 4.0.18 to get it to load on 2018-09.

#61

**Comment by jftsunami** [comment]
@adangel My apologies, I was working with the milestone builds of 2018-09 and since not all of the branding got changed from Photon some of my wires got crossed in the version/naming.

**Comment by corinthian13** [comment]
I installed the Eclipse plugin from https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/ but I have had a similar experience to @mefoster -- all seems installed but no response when run.
You say that we can PMD our code using the regular (i.e. non-plugin) version ? 
Does the regular version have any GUI or is it all on CLI ?

**Comment by adangel** [comment]
@corinthian13 I've just release version 4.0.18. Could you try again please?
I think, this issue should be fixed, as this has been addressed via #61  and #73 .

PMD itself has no GUI on its own. There is a GUI for the Copy-Paste-Detector. There are a couple of integrations for build tools, see https://pmd.github.io/pmd-6.10.0/pmd_userdocs_cli_reference.html for the CLI and https://pmd.github.io/pmd-6.10.0/pmd_userdocs_tools.html for various integrations.

**Comment by corinthian13** [comment]
@adangel: Updated to 4.0.18 and it seems to be working.
But it's even worse than IntelliJ for pedantry !

**Comment by adangel** [comment]
Thanks for testing. Please have a look at the documentation - you'll need to decide, which rules you want to use:

* https://pmd.github.io/pmd-6.10.0/pmd_userdocs_best_practices.html
* https://pmd.github.io/pmd-6.10.0/pmd_userdocs_making_rulesets.html
* Rule Index for Java: https://pmd.github.io/pmd-6.10.0/pmd_rules_java.html

You can have a look at the `rulesets/java/quickstart.xml` ruleset to get started.
