### ISSUE TITLE
Unable to check more than one class without FullBuildEnabled

### ISSUE THREAD

**Issue by phoenix384** [pmd/pmd-eclipse-plugin#7]
With the options
PMD enabled: true
Full build enabled: false

I can let PMD check a single class. But I'm not able to check e.g. a whole package.
The log says "Skipping resource xxx because of fullBuildEnabled flag".
I have to enable "Full build enabled" to be able to check a package. But I want to be able to check a package without letting PMD check everything on a full build.

Perhaps changing ReviewCodeCmd.java:393 to
if (properties.isFullBuildEnabled() || isUserInitiated())...
fixes this?

**Comment by adangel** [comment]
Thanks for the bug report. I've moved this issue over to sourceforge, where all the other bugs are: https://sourceforge.net/p/pmd/bugs/1352/
