### ISSUE TITLE
Global rule management is saved even if cancelled

### ISSUE THREAD

**Issue by phoenix384** [pmd/pmd-eclipse-plugin#76]
Go to Window - Preferences - PMD - Rule Configuration and activate 'Use global rule management'.
Press 'Cancel'. The activation of 'Use global rule management' is saved anyway.

Expected behaviour would be:
The activation of 'Use global rule management' is only saved when clicking 'Apply'.

**Comment by adangel** [comment]
Indeed - the flag is stored as part of the UI state here:
https://github.com/pmd/pmd-eclipse-plugin/blob/bf1b2c8f855382160efda7100d0cee8e21acf615/net.sourceforge.pmd.eclipse.plugin/src/main/java/net/sourceforge/pmd/eclipse/ui/preferences/br/PMDPreferencePage2.java#L539

And `saveUIState()` is called both for `performCancel()`:
https://github.com/pmd/pmd-eclipse-plugin/blob/bf1b2c8f855382160efda7100d0cee8e21acf615/net.sourceforge.pmd.eclipse.plugin/src/main/java/net/sourceforge/pmd/eclipse/ui/preferences/br/PMDPreferencePage2.java#L500-L504

 and `performOk()`:
https://github.com/pmd/pmd-eclipse-plugin/blob/bf1b2c8f855382160efda7100d0cee8e21acf615/net.sourceforge.pmd.eclipse.plugin/src/main/java/net/sourceforge/pmd/eclipse/ui/preferences/br/PMDPreferencePage2.java#L486-L497

The flag should be store not as part of saveUIState() but in performOk() only.
