### ISSUE TITLE
Gutter Markers not Configured Color

### ISSUE THREAD

**Issue by nathanila** [pmd/pmd-eclipse-plugin#85]
In the PMD Preferences, I changed the colors of the priority levels.  However, the gutter markers are still using the old colors.  I have tried restarting Eclipse and re-running PMD.  This did not solve the problem.

In the screenshot, you can see the blue and green triangles in the gutter and the configured colors in the PMD Preferences.

![image](https://user-images.githubusercontent.com/1236594/52074903-30e99c00-2548-11e9-9da1-fe392a43ec63.png)

Note: The colors are correct in the Violations Outline tab.

**Comment by adangel** [comment]
This sounds similar to #42

**Comment by nathanila** [comment]
It is #42.

**Comment by adangel** [comment]
Did you test with the latest version? If so, the problem might not be fixed entirely yet....

**Comment by nathanila** [comment]
I have Eclipse plugin 4.0.18.v20181220-1448 with PMD 6.10.0 installed.

**Comment by adangel** [comment]
I can confirm, this is still a problem.
