### ISSUE TITLE
Add Markers next to Scroll bar

### ISSUE THREAD

**Issue by nathanila** [pmd/pmd-eclipse-plugin#86]
If the Java code has an error, Eclipse IDE puts a red rectangle next to the scroll bar (see image below).  Likewise, if the Java code has a warning, Eclipse IDE puts a yellow rectangle next to the scroll bar.  Please add markers next to the scrollbar for each PMD violation.  This makes it fast to see if there are any problems in the Java file and where those problems are located.  Without this, then I have to scroll through the entire file.

![image](https://user-images.githubusercontent.com/1236594/52078952-baea3280-2551-11e9-976e-5bccef80c256.png)

**Comment by adangel** [comment]
Thanks for reporting. This is being addressed by PR #80 .
