### ISSUE TITLE
Unable to install Eclipse plugin

### ISSUE THREAD

**Issue by rii-mango** [pmd/pmd-eclipse-plugin#9]
My company blocks SourceForge because of its association with malware.  So I am unable to use the eclipse update site.  Is there an alternative, non-SourceForge, update site?  Or can you provide instructions on how to install the plugin not via the update site?  I've tried downloading and installing the plugin in Eclipse Mars, but have been unsuccessful.

**Comment by adangel** [comment]
I've uploaded the latest update site here -> https://github.com/pmd/pmd-eclipse-plugin/releases/tag/4.0.8.v20151204-2156

You should be able to download the zip file, extract it, and point eclipse to your local directory as the update site.
