### ISSUE TITLE
Changing a project's PMD configuration no longer prompts for build

### ISSUE THREAD

**Issue by krallus** [pmd/pmd-eclipse-plugin#94]
PMD Plug-in 4.1.0, when running within either Eclipse 2018-12 or 2019-03 (on Linux), no longer prompts for a build when a project's PMD configuration is changed.

Prior behaviour:
1) Right-click on a Java project and select Properties
2) In the PMD tab, enable or disable a Java rule.
3) Apply and Close
4) A prompt appears: "The project PMD configuration has changed, do you want to rebuild the project now?"

The prompt in 4 above no longer appears, requiring a manual clean and rebuild of the project for the impact of the rule changes to appear in any Eclipse view.

**Comment by adangel** [comment]
This seems to be a side effect of #92

**Comment by adangel** [comment]
It turned out, the problem is unrelated to the mentioned PR.
The problem is a timing problem - sometimes updating the project properties seems to take longer. In that case, we don't see the change yet and assume, there is no need for rebuilding the project...

**Comment by krallus** [comment]
Confirmed fixed in Eclipse 2019-03 (4.11.0) w/ PMD Plug-in 4.2.0. Thanks!
